pipelines:
  Application:
    group: Development

    materials:
      AppGit:
        git: https://github.com/gocd-demo/2016-workshop.git
    stages:
      - build:
          jobs:
            build:
              tasks:
                - exec:
                    command: ./application/build_application.sh
              artifacts:
                - build:
                    source: output
      - unit_test:
          jobs:
            unit_test:
              tasks:
                - exec:
                    command: py.test
                    arguments:
                      - --junitxml
                      - minified-output.xml
                      - "./unit_test/python_test.py"
                    command: xmllint
                    arguments:
                      - --format
                      - minified-output.xml
                      - >
                      - testoutput.xml
              artifacts:
                - test:
                    source: testoutput.xml
      - package:
          jobs:
            package:
              tasks:
                - fetch:
                    stage: build
                    job: build
                    source: output
                - exec:
                    command: ./application/package_application.sh
              artifacts:
                - build:
                    source: installer
