pipelines:
  Application:
    group: Development

    materials:
      AppGit:
        git: https://github.com/gocd-demo/2016-workshop.git
    stages:
      - build:
          jobs:
            build:
              tasks:
                - exec:
                    command: ./application/build_application.sh
              artifacts:
                - build:
                    source: output
      - unit_test:
          jobs:
            unit_test:
              tasks:
                - exec:
                    command: echo
      - package:
          jobs:
            package:
              tasks:
                - fetch:
                    stage: build
                    job: build
                    source: output
                - exec:
                    command: ./application/package_application.sh
              artifacts:
                - build:
                    source: installer
