pipelines:
  Application:
    group: Development

    materials:
      AppGit:
        git: https://github.com/gocd-demo/2016-GoCD-workshop-application.git
    stages:
      - build:
          jobs:
            build:
              tasks:
                - exec:
                    command: ./application/build_application.sh
              artifacts:
                - build:
                    source: output
      - unit_test:
          jobs:
            unit_test:
              artifacts:
                - test:
                    source: report.xml
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - "bundle install"
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - "ruby unit_test/ruby_test.rb --junit"
      - package:
          jobs:
            package:
              tasks:
                - fetch:
                    stage: build
                    job: build
                    source: output
                - exec:
                    command: ./application/package_application.sh
              artifacts:
                - build:
                    source: installer
                - build:
                    source: deploy
