pipelines:
  Staging:
    group: Operations
    locking: on

    materials:
      uat:
        pipeline: UserAcceptance
        stage: Approved
      functional_testing:
        pipeline: FunctionalTesting
        stage: FunctionalTests

    stages:
      - DeployApplications:
          jobs:
            deploy:
              tasks:
                - fetch:
                    pipeline: Application/UserAcceptance
                    stage: package
                    job: package
                    source: installer
                - fetch:
                    pipeline: Application/UserAcceptance
                    stage: package
                    job: package
                    source: deploy
                - exec:
                    command: ./deploy/deploy_application.sh
                    arguments:
                      - Staging
      - VerifyDeployment:
          approval:
            type: success
          jobs:
            verify:
              tasks:
                - exec:
                    command: echo


  Production:
    group: Operations
    locking: on

    materials:
      uat:
        pipeline: Staging
        stage: VerifyDeployment
      security:
        pipeline: SecurityTests
        stage: TestSecurity
      performance:
        pipeline: PerformanceTests
        stage: SoakTest

    stages:
      - DeployApplications:
          jobs:
            deploy:
              tasks:
                - fetch:
                    pipeline: Application/UserAcceptance/Staging
                    stage: package
                    job: package
                    source: installer
                - fetch:
                    pipeline: Application/UserAcceptance/Staging
                    stage: package
                    job: package
                    source: deploy
                - exec:
                    command: ./deploy/deploy_application.sh
                    arguments:
                      - Production
      - VerifyDeployment:
          jobs:
            verify:
              tasks:
                - exec:
                    command: echo
