pipelines:
  PerformanceTests:
    group: Operations
    locking: on

    materials:
      services:
        pipeline: Application
        stage: package
    stages:
      - SoakTest:
          jobs:
            SoakTest:
              tasks:
                - exec:
                    command: echo
                    arguments:
                      - test_performance
